repos:
  # default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.13
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format


  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint-fix
        args:
          - --disable
          - MD013 # line-length
          - MD033 # no-inline-html

  # PyRight (check unresolved imports)
  - repo: local
    hooks:
      - id: nbqa-pyright
        name: nbqa-pyright
        # 'uv run' ensures the hook sees your pyproject.toml dependencies
        entry: uv run nbqa pyright
        language: system
        types: [jupyter]

      - id: cleanup-nbqa-artifacts
        name: cleanup nbqa artifacts
        entry: bash -c 'rm -f **/*_pyright_ipynb.py'
        language: system
        pass_filenames: false
