name: "CI Gatekeeper"

on:
  pull_request:
    # Triggering on these types ensures the gatekeeper
    # restarts if you push new code (synchronize).
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  allchecks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - name: Aggregate Statuses
        uses: wechuli/allcheckspassed@v2
